import './globals.css'
import { Footer, Header } from '@/components'
import { AuthProvider } from '@/contexts/AuthContext'
import { FlipCardContextProvider } from '@/contexts/FlipCardContext'
import { Roboto, Lilita_One, Martel_Sans } from 'next/font/google'
import { Suspense } from 'react'
import Loading from './loading'
import { DBContextProvider } from '@/contexts/DBContext'
import { ReviewContextProvider } from '@/contexts/ReviewContext'
import { DefaultProps } from '@/types'
import { ErrorModalContextProvider } from '@/contexts/ErrorModalContext'

const roboto = Roboto({ weight: ["100", "500", "900"], subsets: ['latin'] })
export const lilitaOne = Lilita_One({ weight: ['400'], subsets: ['latin'] })
export const martelSans = Martel_Sans({ weight: ['700'], subsets: ['latin'] })

export const metadata = {
  title: 'MindPal',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: DefaultProps) {

  return (
    <ErrorModalContextProvider>
      <ReviewContextProvider>
        <DBContextProvider>
          <AuthProvider>
            <html lang="en">
              <body className={`${roboto.className} body-bg  min-h-screen flex flex-col`}>
                <Header />
                <main className='flex-grow flex flex-col px-16 my-4'>
                  <Suspense fallback={<Loading />}>
                    {children}
                  </Suspense>
                </main>
                <Footer />
                <div id='sign-in-modal'></div>
              </body>
            </html>
          </AuthProvider>
        </DBContextProvider>
      </ReviewContextProvider>
    </ErrorModalContextProvider>
  )
}
